### ISSUE TITLE
Tab title is not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#1]
Expected result: Displayed tab title: Shaqo Doon

Actual result: Displayed tab title: React App

**Comment by sebiboga** [comment]
@tonisfr please use lower case in name "shaqo doon"

**Comment by sebiboga** [comment]
**Environment**: BETA (http://zimbor.go.ro)
  URL: http://zimbor.go.ro
  browser: Chrome

**STEPS TO REPRODUCE**:
  1. open URL in browser
  2.  check the title 
  
**EXPECTED RESULTS**:
  the title is shaqo doon

**ACTUAL RESULTS**:
 the title is React App

**Comment by sebiboga** [comment]
retested in latest version
this issue has been fixed
closing the bug

thanks @sergiuavram
