### ISSUE TITLE
Footer should be fixed on the home page

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#10]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

1. open URL in browser
2. click on Companii button
3. scroll all down
4. scroll back to top
5. click on shaqodoon logo

EXPECTED RESULT:
home page should be displayed correctly

ACTUAL RESULT:
footer is missing from homepage

**Comment by sergiuavram** [comment]
please check again, i did an update

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
