### ISSUE TITLE
Header is shaking when you scroll down two times on the mouse wheel

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#11]
Environment: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

1. open URL in browser
2. click on Toate Locurile de Muncă button
3. scroll down two times on mouse wheel

EXPECTED RESULT:
header should get smaller and be displayed correctly

ACTUAL RESULT:
header is shaking

https://user-images.githubusercontent.com/77154604/107030127-d2033100-67b8-11eb-8462-5753efee03bb.mp4

**Comment by sergiuavram** [comment]
solved v0.27

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
