### ISSUE TITLE
text from the footer is not correct

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#16]
Environment: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

1. open URL in browser
2. check the footer

EXPECTED RESULT:
the text is "Creat de echipa shaqo doon."

ACTUAL RESULT:
the text is "Creat de shado doon team."

**Comment by tonisfr** [comment]
@sergiuavram @sarahmartin68 please review the expected result

**Comment by sergiuavram** [comment]
done

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
