### ISSUE TITLE
New colors for the website presentation

### ISSUE THREAD

**Issue by adinananu** [sebiboga/shaqo_doon_frontend#6]
Buna Sergiu, 

Am atasat o schema de culori ca as avem pentru primul live. Am adaugat si codul de culoare in dreptul lor.  Daca sunt nelamuriri te rog sa imi scrii. 
Pe langa culori daca se poate sa si reduci marimea fieldurilor unde sunt afisate firmele, deoarece sunt prea mari vizual fata de restul site-ului. Eventual cand lucrezi la ele si sunt prin jur putem discuta.

Merci mult, 
Adina
![1-Header-14](https://user-images.githubusercontent.com/36031095/106480272-df1bd980-64b3-11eb-8d8c-d880c7b0f0f4.jpg)
![2-Companii-14](https://user-images.githubusercontent.com/36031095/106480277-e04d0680-64b3-11eb-9238-fb37116b4768.jpg)
![3-Locuri-de-munca14](https://user-images.githubusercontent.com/36031095/106480279-e04d0680-64b3-11eb-8d07-25b6e9070c6f.jpg)

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
