### ISSUE TITLE
Footer should be fixed on bottom

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#7]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. look at the footer

EXPECTED RESULTS:
footer is positioned on the bottom of the page

ACTUAL RESULTS:
footer is positioned under the buttons

**Comment by sergiuavram** [comment]
solved v0.24

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
