### ISSUE TITLE
Welcome message is not fixed

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_frontend#8]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. look at the welcome message
 3. scroll down

EXPECTED RESULTS:
welcome message should be fixed

ACTUAL RESULTS:
welcome message is hiding under the header

**Comment by tonisfr** [comment]
![bug3](https://user-images.githubusercontent.com/77154604/106925469-cb24e180-6718-11eb-8523-e82537b5670a.png)
![bug4](https://user-images.githubusercontent.com/77154604/106925474-cbbd7800-6718-11eb-81da-463046ef437b.jpg)

**Comment by sergiuavram** [comment]
can you explain why this is a bug?

For now there is just one line message on home page: the welcome message.
I am looking forward to create a larger one.

as cu can notice all scroll-able content goes under header.

**Comment by tonisfr** [comment]
I thought that we go LIVE with that message. 
If you replace that with something else is ok. 
But if you replace that with a carousel for example make sure that is fixed and it is not going under the header.

**Comment by sebiboga** [comment]
not targeted for MVP
